config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  root to: 'pages#index'
  devise_for :users
  resources :twitter_users
  resources :comments, only: %i[create destroy]
  mount Sidekiq::Web => '/sidekiq'
  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tweet
  after_create_commit { RenderCommentJob.perform_now self }
  after_destroy_commit { DeleteCommentJob.perform_now self }
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :twitter_user
  has_many :comments, dependent: :destroy
  # validates_presence_of %i[full_text created]
  # validates_each %i[retweet_count favorite_count], allow_nil: true

  scope :recent_ones, -> {order(created: :desc)}
end

app/models/twitter_user.rb
class TwitterUser < ApplicationRecord
  before_validation :make_name_correct, if: :name_changed?
  before_save :set_default, on: %i[create update]

  VALID_NAME_REGEX = /[^0-9A-Za-z]/

  belongs_to :user
  has_many :tweets, dependent: :destroy

  validates :owner, presence: true
  validates :name, uniqueness: true, presence: true

  validates :uid, presence: false, allow_nil: true
  validate :monitored, on: :create

  scope :popular_first, -> { order(followers: :desc) }

  def without_avatar
    TwitterUser.where(image_url: nil)
  end

  def make_name_correct
    return unless name
    name.gsub!(VALID_NAME_REGEX, '')
    name.capitalize!
  end

  def set_default
    self.uid ||= 0
  end

  def monitored
    errors.add(:owner, 'already exists in your twitter user list') if
        TwitterUser.exists?(owner: owner)
  end
end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_NAME_REGEX = /[a-zA-Z0-9]/
  before_save :capitalize_name, on: %i[create update]
  after_create :send_email

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :twitter_users, dependent: :destroy

  validates :name, presence: true, format: { with: VALID_NAME_REGEX,
                                             message: 'only allows letters and digits' },
                   uniqueness: true
  validates :email, presence: true, uniqueness: true,
                    format: { with: VALID_EMAIL_REGEX,
                              message: 'invalid email' }

  validates :encrypted_password, presence: true,
                                 length: { minimum: 6 },
                                 allow_blank: false

  scope :desc, -> { order(created_at: :desc) }
  scope :asc,  -> { order(created_at: :asc) }
  scope :alphabetic, -> { order(name: :asc) }

  def capitalize_name
    name.capitalize!
  end

  def send_email
    UserMailer.registration(self).deliver
  end

  def monitoring
    twitter_users.count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  require 'twitter'

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    result = Comment::Create.(params: params)
    @comment = result[:model]
  end

  def destroy
    result = Comment::Destroy.(params: params)
    @comment = result[:model]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    result = Page::Index.(params: params, current_user: current_user, signed_in: user_signed_in?)
    @tweets_feed = result[:tweets]
  end
end

app/controllers/twitter_users_controller.rb
class TwitterUsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @twitter_users = TwitterUser::Index.call(current_user: current_user)['model']
  end

  def show
    result = TwitterUser::Show.call(params: params.permit(:id), current_user: current_user)
    @twitter_user = result[:model]
    @tweets = result[:tweets]
  end

  def new
    @twitter_user = TwitterUser::New.call(current_user: current_user)['model']
  end

  def create
    result = TwitterUser::Create.(params: params, current_user: current_user)
    if result.success?
      redirect_to twitter_users_path, flash: { success: 'New user is successfuly added!' }
    else
      redirect_to new_twitter_user_path, flash: { danger: 'Your new user has invalid data!'}
    end
  end

  def edit
    result = TwitterUser::Edit.call( params: params.permit(:id) )
    @twitter_user = result[:model]
  end

  def update
    result = TwitterUser::Update.call( params: params)
    @twitter_user = result[:model]
    if result.success?
      redirect_to @twitter_user, flash: { success: 'Profile updated' }
    else
      redirect_to edit_twitter_user_path, flash: { danger: "Profile can`t be updated, fill the fields" }
    end
  end

  def destroy
    TwitterUser::Destroy.call( params: params.permit(:id) )
    redirect_to twitter_users_path, flash: { success: 'User deleted' }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def job_status(job_id)
  	binding.pry
    Sidekiq::Status::complete?(job_id)  
  end 
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.slim
.comment-list[id="#{dom_id(comment)}"]
  .row
    .col-md-12
      p = comment.body
      p = link_to 'Delete', comment_path(comment.id), method: :delete, remote: true,
                data: {confirm: 'Are you certain you want to delete this comment?'},
                id: "#{dom_id(comment)}"

app/views/comments/_comment_form.html.slim
.comment-form
  = form_for Comment.new, remote: true do |f|
    = f.hidden_field :tweet_id, value: tweet_id
    = f.text_field :body, id: "body_input-#{tweet_id}"
    = f.submit

app/views/comments/_comments.html.slim
div.comments data-tweet-id="#{object.id}"
  = render partial: 'comments/comment', collection: object.comments, as: :comment
.comment-form
  = render 'comments/comment_form', tweet_id: object.id

app/views/comments/create.js.erb
// $("div#comments[data-tweet-id='<%=@comment.tweet_id%>']").append('<%= render partial: 'comments/comment', locals: { comment: @comment }, layout: false, status: :created%>')
// $("#body_input-<%=@comment.tweet_id%>").val('');

app/views/comments/destroy.js.erb
// $('#comment_<%= @comment.id %>').fadeOut(200);

app/views/layouts/_main_menu.html.slim
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      = link_to 'Twitter Monitor', root_path, class: 'navbar-brand'
    #navbar
      ul.nav.navbar-nav.navbar-right
        li
          = link_to 'Home', root_path
        - if user_signed_in?
          li.dropdown
            a.dropdown-toggle[href="#" data-toggle="dropdown"]
              = current_user.name
              b.caret
            ul.dropdown-menu[role="menu"]
              li
                = link_to 'New Twitter', new_twitter_user_path
              li
                = link_to 'User list', twitter_users_path
              li
                = link_to 'Settings', edit_user_registration_path
              li
                = link_to 'Log out', destroy_user_session_path, method: :delete
        - else
          li
            = link_to 'Log In', new_user_session_path
          li
            = link_to 'Sign Up', new_user_registration_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | TwitterMonitor
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .container
      = render 'layouts/main_menu'
      - flash.each do |message_type,message|
        = content_tag(:div, message, class: "alert alert-#{message_type}")
      = yield

app/views/pages/_side_bar.html.slim
aside.card.col-md-4
  .card-body
    h1
      = current_user.name
    .text-center
      =  image_tag gravatar_image_url(current_user.email, size: 150), alt: current_user.name
    section.stats
      h4
        | Monitoring
        = " #{pluralize(current_user.monitoring, 'user')}"
      h4
        | Your email:
        = " #{current_user.email}"
    .row
      .col-md-4
        = link_to 'New Twitter', new_twitter_user_path, class: 'btn btn-primary'
      .col-md-6
        = link_to 'Users list', twitter_users_path, class: 'btn btn-success '

app/views/pages/index.html.slim
- if user_signed_in?
  .row
    = render 'side_bar'
    = render 'twitter_users/tweets', tweets: @tweets_feed
- else
  .center.jumbotron
    h1
      | Welcome!
    p
      | Register to get started.
    p
      = link_to 'Register', new_user_registration_path, class: 'btn btn-primary btn-lg'

app/views/shared/_errors.html.slim
- if object.errors.any?
  .error_explanation
    .alert.alert-danger
      |  The form contains 
      = pluralize(object.errors.count, "error")
    ul
      - object.errors.full_messages.each do |msg|
        li
          = msg

app/views/twitter_users/_form.html.slim
= form_for (@twitter_user)  do |f|
  = render 'shared/errors', object: @twitter_user
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
    = f.label :owner
    = f.text_field :owner, class: 'form-control', placeholder: 'Enter a valid owner name'
  = f.submit text_button , class: 'btn btn-primary'

app/views/twitter_users/_tweets.html.slim
.col-md-8
  - tweets.each do |tweet|
    .col-md-8
      .card.box-shadow-0.border-primary.bg-transparent.tweet
        .card-content.collapse.show
          .card-header
            = image_tag(tweet.twitter_user.image_url, size:50)
            span.h4 =" #{tweet.twitter_user.name}"
          .card-body
            p.mb-2
              = auto_link(tweet.full_text, html: {target: '_blank'})
            .tweet-footer.card-footer.border-0.text-muted
              span
                = "posted #{time_ago_in_words(tweet.created)} ago "
              span.float-right
                i.fa.fa-retweet
                  |&nbsp;
                  = number_to_human(tweet.retweet_count, precision: 2)
                i.fa.fa-heart.pink
                  |&nbsp;
                = number_to_human(tweet.favorite_count, precision: 2)
                = link_to "#{tweet.uri}", target: '_blank' do
                  i.text-secondary.fa.fa-external-link.ml-1
            = render 'comments/comments', object: tweet

app/views/twitter_users/_twitter_user_info.html.slim
aside.card.col-md-4
  .card-body
    div
      h1
        = @twitter_user.name
    .text-center
      = image_tag  @twitter_user.image_url, alt: @twitter_user.name, size: 150
    section.stats
      p
        | Description: 
        = @twitter_user.description
      p
        | Created at: 
        = @twitter_user.created_at_twitter.strftime("%m/%d/%Y")
      p
        | User owner id: 
        = @twitter_user.owner
      p
        | Followers: 
        = number_to_human(@twitter_user.followers)
      p
        | Following: 
        = number_to_human(@twitter_user.following)

app/views/twitter_users/edit.html.slim
.col-md-6.col-md-offset-3
  h1
    | Edit
  = render 'form', text_button: 'Update'

app/views/twitter_users/index.html.slim
h1
  | List of users
.row.text-right
  .col-md-12
    = link_to  new_twitter_user_path, class: 'btn btn-success', id: 'add-button' do
      i.fa.fa-plus
.text-align-center
  table.table.table-bordered
    thead
      tr
        th.col-md-3
          | Name
        th.col-md-3
          | Owner
        th.col-md-3
          | Operations
        th.col-md-3
          | Status
    tbody
      - @twitter_users.each do |user|
        tr
          td
            = link_to user.name,  twitter_user_path(user)
          td
            = user.owner
          td
            .row.btn-group
              .col-md-3
                = link_to user , class: 'btn btn-warning btn-md' do
                  i.fa.fa-eye
              .col-md-3
                = link_to edit_twitter_user_path(user), class: 'btn btn-danger btn-md' do
                  i.fa.fa-edit
              .col-md-3
                = link_to user, method: :delete, data: { confirm: 'Are you sure?' },
                class: 'btn btn-primary btn-md' do
                  i.fa.fa-trash
          td        
            .col-md-6
              p id="notifications-#{user.id}"
                - if job_status(user.job_id)
                  | Completed
                - else 
                  | Pending

app/views/twitter_users/new.html.slim
.col-md-6.col-md-offset-3
  h1
    | Add a twitter user
  = render 'form', text_button: 'Add new twitter'

app/views/twitter_users/show.html.slim
.row
  = render 'twitter_user_info'
  = render 'tweets', tweets: @tweets